build:
  main: cmd/booster/main.go
  binary: booster
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
    - dragonfly
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ldflags: -s -w -X main.Version={{.Version}} -X main.BuildTime={{.Date}}
archive:
  replacements:
    amd64: 64bit
    386: 32bit
brew:
  # Reporitory to push the tap to.
  github:
    owner: danielmorandini
    name: homebrew-tap

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: danielmorandini
    email: danielmorandini@me.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Your app's homepage.
  # Default is empty.
  homepage: "https://booster.tecnoporto.co/"

  # Your app's description.
  # Default is empty.
  description: "peer-to-peer network interface balancer"

  skip_upload: true
